const firstName = "Arezoo";
const lastName = "Yousefi" ;
const age = 41;
const dateOfBirth = "10/12/1979";
const address = "1530 Salisbury Ave";
console.log('My first name:', firstName);
console.log('My last name:', lastName);
console.log('I am ', age ,'years old.');
console.log('I was born in ', dateOfBirth);
console.log('My address is ', address);