const iceCreamFlavours = ["caffee", "moka", "chocolate", "coconut", "vanilla", "nut", "orange", "strawberry", "blueberry", "rasberry"];
const flavour1 = iceCreamFlavours.pop();
const flavour2 = iceCreamFlavours.pop();
const flavour3 = iceCreamFlavours.pop();
const flavour4 = iceCreamFlavours.pop();
const flavour5 = iceCreamFlavours.pop();
const flavour6 = iceCreamFlavours.pop();
const flavour7 = iceCreamFlavours.pop();
const flavour8 = iceCreamFlavours.pop();
const flavour9 = iceCreamFlavours.pop();
const flavour10 = iceCreamFlavours.pop();
console.log(flavour1);
console.log(flavour2);
console.log(flavour3);
console.log(flavour4);
console.log(flavour5);
console.log(flavour6);
console.log(flavour7);
console.log(flavour8);
console.log(flavour9);
console.log(flavour10);